# Site settings
title: Primordial Code
email: alessandro.giorgetti@live.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging in progress... on .NET, Html, JavaScript...
baseurl: "" # the subpath of your site, e.g. /blog/
# Change url to your domain. Leave localhost server or blank when working locally.
url: "http://www.primordialcode.com" #"http://agiorgetti.github.io" # the base hostname & protocol for your site
twitter_username: a_giorgetti	
github_username:  agiorgetti

# Build settings
encoding: utf-8
markdown: kramdown
#highlighter: rouge

# Theme specific
# logo 150*150
logo:             logo.png 
disqus_shortname: primordialcode
# Assign a default image for your site's header and footer
#default_bg:       some-image.jpg
search:           true
share:            true
# Read Time is a calculator to provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"

# Owner/author information
owner:
  name:           Alessandro Giorgetti
  avatar:         me.png
  email:          alessandro.giorgetti@live.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    #Some Details about yourself
  # Social networking links used in footer. Update and remove as you like.
  twitter:  A_Giorgetti
  facebook: giorgetti.alessandro
  github: AGiorgetti
  # linkedin not working?
  linkedin: giorgettialessandro
  #instagram:
  #tumblr:
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:    "http://plus.google.com/123123123123132123"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Archive
    url: /archive
  #- title: Categories
  #  url: /categories
  - title: Tags
    url: /tags
  - title: Privacy
    url: /privacy
  - title: About
    url: /about-me

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
# this configuration has been replaced by the new 'highlighter'
#pygments:    true
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
# original /:categories/:title
# per renderlo simile a dexter...
permalink:  /blog/post/:title 

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class