# Site settings
title: Primordial Code
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Writing code as a CaveMan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
encoding: utf-8
markdown: kramdown
highlighter: rouge

